distributionBase=MAVEN_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=MAVEN_USER_HOME
zipStorePath=wrapper/dists
